# Generated by Django 3.1.1 on 2020-09-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cod_empresa', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('segmento', models.PositiveSmallIntegerField(choices=[(1, 'SOMA'), (2, 'BOVESPA NIVEL 2'), (3, 'BOLSA'), (4, 'NOVO MERCADO'), (5, 'BOVESPA NIVEL 1'), (6, 'MAIS'), (7, 'FIP MT'), (8, 'FIP IE'), (9, 'FIP EE'), (10, 'MAIS NIVEL 2')], verbose_name='Segmento')),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Capital')),
                ('qtd_ordinarias', models.PositiveBigIntegerField(verbose_name='Quant. Ações Ordinárias')),
                ('qtd_preferenciais', models.PositiveBigIntegerField(verbose_name='Quant. Ações Preferenciais')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
